// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/*
 * Copyright (C) 2006 Michael Emmel mike.emmel@gmail.com. All rights reserved.
 * Copyright (C) 2008, 2009 Google Inc.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE, DATA, OR
 * PROFITS, OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef UI_EVENTS_KEYCODES_KEYBOARD_CODES_POSIX_H_
#define UI_EVENTS_KEYCODES_KEYBOARD_CODES_POSIX_H_

namespace ui {

enum KeyboardCode {
  VKEY_CANCEL = 0x03,
  VKEY_BACK = 0x08,
  VKEY_TAB = 0x09,
  VKEY_BACKTAB = 0x0A,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_CLEAR = 0x0C,
#endif
  VKEY_RETURN = 0x0D,
  VKEY_SHIFT = 0x10,
  VKEY_CONTROL = 0x11,
  VKEY_MENU = 0x12,
  VKEY_PAUSE = 0x13,
  VKEY_CAPITAL = 0x14,
  VKEY_KANA = 0x15,
  VKEY_HANGUL = 0x15,
  VKEY_JUNJA = 0x17,
  VKEY_FINAL = 0x18,
  VKEY_HANJA = 0x19,
  VKEY_KANJI = 0x19,
  VKEY_ESCAPE = 0x1B,
  VKEY_CONVERT = 0x1C,
  VKEY_NONCONVERT = 0x1D,
  VKEY_ACCEPT = 0x1E,
  VKEY_MODECHANGE = 0x1F,
  VKEY_SPACE = 0x20,
  VKEY_PRIOR = 0x21,
  VKEY_NEXT = 0x22,
  VKEY_END = 0x23,
  VKEY_HOME = 0x24,
  VKEY_LEFT = 0x25,
  VKEY_UP = 0x26,
  VKEY_RIGHT = 0x27,
  VKEY_DOWN = 0x28,
  VKEY_SELECT = 0x29,
  VKEY_PRINT = 0x2A,
  VKEY_EXECUTE = 0x2B,
  VKEY_SNAPSHOT = 0x2C,
  VKEY_INSERT = 0x2D,
  VKEY_DELETE = 0x2E,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_HELP = 0x2F,
#endif
  VKEY_0 = 0x30,
  VKEY_1 = 0x31,
  VKEY_2 = 0x32,
  VKEY_3 = 0x33,
  VKEY_4 = 0x34,
  VKEY_5 = 0x35,
  VKEY_6 = 0x36,
  VKEY_7 = 0x37,
  VKEY_8 = 0x38,
  VKEY_9 = 0x39,
  VKEY_A = 0x41,
  VKEY_B = 0x42,
  VKEY_C = 0x43,
  VKEY_D = 0x44,
  VKEY_E = 0x45,
  VKEY_F = 0x46,
  VKEY_G = 0x47,
  VKEY_H = 0x48,
  VKEY_I = 0x49,
  VKEY_J = 0x4A,
  VKEY_K = 0x4B,
  VKEY_L = 0x4C,
  VKEY_M = 0x4D,
  VKEY_N = 0x4E,
  VKEY_O = 0x4F,
  VKEY_P = 0x50,
  VKEY_Q = 0x51,
  VKEY_R = 0x52,
  VKEY_S = 0x53,
  VKEY_T = 0x54,
  VKEY_U = 0x55,
  VKEY_V = 0x56,
  VKEY_W = 0x57,
  VKEY_X = 0x58,
  VKEY_Y = 0x59,
  VKEY_Z = 0x5A,
  VKEY_LWIN = 0x5B,
  VKEY_COMMAND = VKEY_LWIN,  // Provide the Mac name for convenience.
  VKEY_RWIN = 0x5C,
  VKEY_APPS = 0x5D,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_SLEEP = 0x5F,
#endif
  VKEY_NUMPAD0 = 0x60,
  VKEY_NUMPAD1 = 0x61,
  VKEY_NUMPAD2 = 0x62,
  VKEY_NUMPAD3 = 0x63,
  VKEY_NUMPAD4 = 0x64,
  VKEY_NUMPAD5 = 0x65,
  VKEY_NUMPAD6 = 0x66,
  VKEY_NUMPAD7 = 0x67,
  VKEY_NUMPAD8 = 0x68,
  VKEY_NUMPAD9 = 0x69,
  VKEY_MULTIPLY = 0x6A,
  VKEY_ADD = 0x6B,
  VKEY_SEPARATOR = 0x6C,
  VKEY_SUBTRACT = 0x6D,
  VKEY_DECIMAL = 0x6E,
  VKEY_DIVIDE = 0x6F,
  VKEY_F1 = 0x70,
  VKEY_F2 = 0x71,
  VKEY_F3 = 0x72,
  VKEY_F4 = 0x73,
  VKEY_F5 = 0x74,
  VKEY_F6 = 0x75,
  VKEY_F7 = 0x76,
  VKEY_F8 = 0x77,
  VKEY_F9 = 0x78,
  VKEY_F10 = 0x79,
  VKEY_F11 = 0x7A,
  VKEY_F12 = 0x7B,
  VKEY_F13 = 0x7C,
  VKEY_F14 = 0x7D,
  VKEY_F15 = 0x7E,
  VKEY_F16 = 0x7F,
  VKEY_F17 = 0x80,
  VKEY_F18 = 0x81,
  VKEY_F19 = 0x82,
  VKEY_F20 = 0x83,
  VKEY_F21 = 0x84,
  VKEY_F22 = 0x85,
  VKEY_F23 = 0x86,
  VKEY_F24 = 0x87,
  VKEY_NUMLOCK = 0x90,
  VKEY_SCROLL = 0x91,
  VKEY_LSHIFT = 0xA0,
  VKEY_RSHIFT = 0xA1,
  VKEY_LCONTROL = 0xA2,
  VKEY_RCONTROL = 0xA3,
  VKEY_LMENU = 0xA4,
  VKEY_RMENU = 0xA5,
  VKEY_BROWSER_BACK = 0xA6,
  VKEY_BROWSER_FORWARD = 0xA7,
  VKEY_BROWSER_REFRESH = 0xA8,
  VKEY_BROWSER_STOP = 0xA9,
  VKEY_BROWSER_SEARCH = 0xAA,
  VKEY_BROWSER_FAVORITES = 0xAB,
  VKEY_BROWSER_HOME = 0xAC,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_VOLUME_MUTE = 0xAD,
  VKEY_VOLUME_DOWN = 0xAE,
  VKEY_VOLUME_UP = 0xAF,
#endif
  VKEY_MEDIA_NEXT_TRACK = 0xB0,
  VKEY_MEDIA_PREV_TRACK = 0xB1,
  VKEY_MEDIA_STOP = 0xB2,
  VKEY_MEDIA_PLAY_PAUSE = 0xB3,
  VKEY_MEDIA_LAUNCH_MAIL = 0xB4,
  VKEY_MEDIA_LAUNCH_MEDIA_SELECT = 0xB5,
  VKEY_MEDIA_LAUNCH_APP1 = 0xB6,
  VKEY_MEDIA_LAUNCH_APP2 = 0xB7,
  VKEY_OEM_1 = 0xBA,
  VKEY_OEM_PLUS = 0xBB,
  VKEY_OEM_COMMA = 0xBC,
  VKEY_OEM_MINUS = 0xBD,
  VKEY_OEM_PERIOD = 0xBE,
  VKEY_OEM_2 = 0xBF,
  VKEY_OEM_3 = 0xC0,
  VKEY_OEM_4 = 0xDB,
  VKEY_OEM_5 = 0xDC,
  VKEY_OEM_6 = 0xDD,
  VKEY_OEM_7 = 0xDE,
  VKEY_OEM_8 = 0xDF,
  VKEY_OEM_102 = 0xE2,
  VKEY_OEM_103 = 0xE3,  // GTV KEYCODE_MEDIA_REWIND
  VKEY_OEM_104 = 0xE4,  // GTV KEYCODE_MEDIA_FAST_FORWARD
  VKEY_PROCESSKEY = 0xE5,
  VKEY_PACKET = 0xE7,
  VKEY_OEM_ATTN = 0xF0,      // JIS DomKey::ALPHANUMERIC
  VKEY_OEM_FINISH = 0xF1,    // JIS DomKey::KATAKANA
  VKEY_OEM_COPY = 0xF2,      // JIS DomKey::HIRAGANA
  VKEY_DBE_SBCSCHAR = 0xF3,  // JIS DomKey::HANKAKU
  VKEY_DBE_DBCSCHAR = 0xF4,  // JIS DomKey::ZENKAKU
  VKEY_OEM_BACKTAB = 0xF5,   // JIS DomKey::ROMAJI
  VKEY_ATTN = 0xF6,          // DomKey::ATTN or JIS DomKey::KANA_MODE
  VKEY_CRSEL = 0xF7,
  VKEY_EXSEL = 0xF8,
  VKEY_EREOF = 0xF9,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_PLAY = 0xFA,
#endif
  VKEY_ZOOM = 0xFB,
  VKEY_NONAME = 0xFC,
  VKEY_PA1 = 0xFD,
  VKEY_OEM_CLEAR = 0xFE,
  VKEY_UNKNOWN = 0,

  // POSIX specific VKEYs. Note that as of Windows SDK 7.1, 0x97-9F, 0xD8-DA,
  // and 0xE8 are unassigned.
  VKEY_WLAN = 0x97,
#if !defined(OS_TIZEN_TV_PRODUCT)
  VKEY_POWER = 0x98,
#endif
  VKEY_ASSISTANT = 0x99,
  VKEY_SETTINGS = 0x9A,
  VKEY_BRIGHTNESS_DOWN = 0xD8,
  VKEY_BRIGHTNESS_UP = 0xD9,
  VKEY_KBD_BRIGHTNESS_DOWN = 0xDA,
  VKEY_KBD_BRIGHTNESS_UP = 0xE8,

  // Windows does not have a specific key code for AltGr. We use the unused 0xE1
  // (VK_OEM_AX) code to represent AltGr, matching the behaviour of Firefox on
  // Linux.
  VKEY_ALTGR = 0xE1,
  // Windows does not have a specific key code for Compose. We use the unused
  // 0xE6 (VK_ICO_CLEAR) code to represent Compose.
  VKEY_COMPOSE = 0xE6,

#if defined(OS_TIZEN_TV_PRODUCT)
  // TV keys on remote controller.
  // Virtual keys defined in http://www.atsc.org/cms/standards/a100/a_100_2.pdf
  // Same volume virtual keys are already defined in Windows virtual keys but we
  // overlap with the keys defined in DTV.
  // VKEY_PLAY
  // VKEY_VOLUME_UP
  // VKEY_VOLUME_DOWN
  // VKEY_VOLUME_MUTE

  VKEY_RED = 0x193,
  VKEY_GREEN = 0x194,
  VKEY_YELLOW = 0x195,
  VKEY_BLUE = 0x196,
  VKEY_GREY = 0x197,
  VKEY_BROWN = 0x198,

  VKEY_DTV_RETURN = 0x2719,
  VKEY_DTV_HOME = 0x2757,
  VKEY_SOURCE = 0x2758,
  VKEY_CH_LIST = 0x2759,

  VKEY_POWER = 0x199,
  VKEY_DTV_MENU = 0x2795,
  VKEY_GUIDE = 0x1CA,
  VKEY_ADDDEL = 0x1AD,
  VKEY_AUTO_PROGRAM = 0x1B9,
  VKEY_FAVCH = 0x1B1,
  VKEY_BT_DUALVIEW = 0x1BB,
  VKEY_SUB_TITLE = 0x1CC,

  VKEY_REWIND = 0x19C,
  VKEY_STOP = 0x19D,
  VKEY_PLAY = 0x19F,
  VKEY_RECORD = 0x1A0,
  VKEY_FAST_FWD = 0x1A1,

  VKEY_CHANNEL_UP = 0x1AB,
  VKEY_CHANNEL_DOWN = 0x1AC,

  VKEY_VOLUME_UP = 0x1BF,
  VKEY_VOLUME_DOWN = 0x1C0,
  VKEY_VOLUME_MUTE = 0x1C1,

  VKEY_INFO = 0x1C9,

  VKEY_REPEAT = 0x2799,
  VKEY_ASPECT = 0x279C,
  VKEY_PMODE = 0x279D,
  VKEY_HDMI = 0x279F,
  VKEY_USBHUB_SWITCH = 0x27A0,
  VKEY_EMANUAL = 0x27A2,
  VKEY_TOOLS = 0x2797,
  VKEY_MORE = 0x27A4,
  VKEY_FACTORY = 0x27A5,
  VKEY_SLEEP = 0x27A6,
  VKEY_TV = 0x27A9,
  VKEY_DTV = 0x27AA,
  VKEY_STB_POWER = 0x27AB,
  VKEY_PANEL_DOWN = 0x27AD,
  VKEY_CONVERGENCE = 0x27AE,
  VKEY_BT_COLOR_MECHA = 0x27AF,
  VKEY_STILL_PICTURE = 0x27B0,
  VKEY_BT_TRIGGER = 0x27B1,
  VKEY_BT_HOTVK = 0x27B2,
  VKEY_BT_DEVICE = 0x27B3,
  VKEY_BT_CONTENTSBAR = 0x27B4,
  VKEY_GAME = 0x27B5,
  VKEY_PIP_CHUP = 0x27B7,
  VKEY_PIP_CHDOWN = 0x27B8,
  VKEY_ANTENA = 0x27B9,
  VKEY_PANEL_ENTER = 0x27BB,
  VKEY_LINK = 0x27BC,
  VKEY_PANEL_UP = 0x27BD,

  VKEY_ANGLE = 0x27C1,
  VKEY_WHEEL_LEFT = 0x27C2,
  VKEY_WHEEL_RIGHT = 0x27C3,
  VKEY_CONTENTS = 0x2757,
  VKEY_PANEL_EXIT = 0x27C5,
  VKEY_EXIT = 0x27C6,

  VKEY_MBR_TV = 0x27C7,
  VKEY_MBR_STB_GUIDE = 0x27C8,
  VKEY_MBR_BD_POPUP = 0x27C9,
  VKEY_MBR_BDDVD_POWER = 0x27CA,
  VKEY_MBR_SETUP_FAILURE = 0x27CB,
  VKEY_MBR_SETUP = 0x27CC,
  VKEY_MBR_WATCH_TV = 0x27CD,

  VKEY_PRECH = 0x27CE,
  VKEY_RECOMMEND_SEARCH_TOGGLE = 0x27D0,
  VKEY_BT_NUMBER = 0x27D1,
  VKEY_16_9 = 0x27D2,
  VKEY_MTS = 0x27D3,
  VKEY_SMODE = 0x27D5,
  VKEY_3SPEED = 0x27D6,
  VKEY_3D = 0x27D7,
  VKEY_TTX_MIX = 0x27D8,
  VKEY_SRSTSXT = 0x27D9,
  VKEY_WIFI_PAIRING = 0x27DA,
  VKEY_BT_SAMSUNG_APPS = 0x27E3,
  VKEY_W_LINK = 0x2757,
  VKEY_ESAVING = 0x27E5,
  VKEY_CLEAR = 0x27E6,
  VKEY_TV_SNS = 0x27E9,
  VKEY_DVR = 0x27EA,
  VKEY_APP_LIST = 0x27EB,
  VKEY_CAMERA = 0x27EC,
  VKEY_CAPTION = 0x27ED,
  VKEY_ZOOM1 = 0x27EE,
  VKEY_PANEL_PLUS = 0x27EF,
  VKEY_BT_VOICE = 0x27F0,
  VKEY_SEARCH = 0x27F1,
  VKEY_PANEL_MINUS = 0x27F3,
  VKEY_SOCCER_MODE = 0x27F4,
  VKEY_FUNCTIONS_AMAZON = 0x27F5,
  VKEY_AD = 0x27F6,
  VKEY_REWIND_ = 0x27F8,
  VKEY_FF_ = 0x27F9,
  VKEY_FUNCTIONS_NETFLIX = 0x27FA,
  VKEY_PIP_ONOFF = 0x27FB,
  VKEY_MBR_WATCH_MOVIE = 0x27FC,
  VKEY_MBR_STBBD_MENU = 0x27FD,
  VKEY_MBR_SETUP_CONFIRM = 0x27FE,
  VKEY_FAMILYHUB = 0x27FF,
  VKEY_ANYVIEW = 0x2800,

  VKEY_PAGE_LEFT = 0x2809,
  VKEY_PAGE_RIGHT = 0x280A,

  VKEY_SOFT_WAKE_UP = 0x2804,
  VKEY_PANEL_ON = 0x280B,
  VKEY_PLAY_BACK = 0x280C,
  VKEY_EXTRA = 0x280D,
  VKEY_COLOR = 0x2891,

  VKEY_ALARM = 0x28B2,
  VKEY_HOTEL_MOVIES = 0x28FE,
  VKEY_HOTEL_LANGUAGE = 0x28FF,
  VKEY_HOTEL_TV_GUIDE = 0x2900,
  VKEY_HOTEL_APPS_GUEST = 0x2901,
  VKEY_NOISE_REDUCTION = 0x2917,
  VKEY_HELP = 0x2918,
  VKEY_NR = 0x2919,
  VKEY_HOTEL_ROOM_CONTROL = 0x291A,

  // TV IME "Select" key, no X Server keycode, 0xFF60 ISF code.
  VKEY_IME_DONE = 0xFF60,
  // TV IME "Cancel" key, no X Server keycode, 0xFF69 ISF code.
  VKEY_IME_CANCEL = 0xFF69,

#endif
};

}  // namespace ui

#endif  // UI_EVENTS_KEYCODES_KEYBOARD_CODES_POSIX_H_
